### ISSUE TITLE
html tags rendered as plain text

### ISSUE THREAD

**Issue by akashsharma99** [anonthedev/booksuno#2]
html tags getting rendered as plain text for the audio book description.  

![image](https://github.com/anonthedev/booksuno/assets/22654711/c97a5419-3a43-4eae-b6e4-c9396a05d1b9)

**Comment by anonthedev** [comment]
aah didn't notice that, should be a simple fix just add ```dangerouslySetInnerHTML``` to the <p> tag in which the description is there and pass the description in the ```dangerouslySetInnerHTML```

Raise a PR if you want or just tell me I'll edit it myself.

**Comment by akashsharma99** [comment]
I'll raise a PR 👍
